### ISSUE TITLE
No compatible package found for 'en_US_core_news_lg'

### ISSUE THREAD

**Issue by mhmcdonald** [tokern/piicatcher_spacy#2]
I'm testing out this library and when I try running this command:
`piicatcher detect --source-name pii_test --scan-type data`

I get the following error: 
`No compatible package found for 'en_US_core_news_lg' (spaCy v3.2.1)`

I'm using these versions:
python = "3.8.5"
piicatcher = "0.19.1"
piicatcher-spacy = "^0.1.0-alpha.3"
spacy = "3.2.1"

**Comment by vrajat** [comment]
The detector should have downloaded that spacy package automatically. I'll try to reproduce the error.

**Comment by vrajat** [comment]
That model is not available anymore. I have set the default model to "en_core_web_md". This should be fixed in v0.1.1 that should be generated in a few minutes.
