### ISSUE TITLE
Unable to install when using Python version 3.9.12

### ISSUE THREAD

**Issue by ian-lewis-d** [tokern/piicatcher_spacy#4]
I'm trying to do a deep scan using piicatcher but cannot install piicatcher_spacy.

` 
(venv) user$ pip3 install piicatcher_spacy

ERROR: Ignored the following versions that require a different python version: 0.1.0.dev3 Requires-Python >=3.6.2,<3.9; 0.1.1 Requires-Python >=3.6.2,<3.9

ERROR: Could not find a version that satisfies the requirement piicatcher_spacy (from versions: none)

ERROR: No matching distribution found for piicatcher_spacy

(venv) user$ python3 -V

Python 3.9.12
`

Is there an alternative approach for this?

**Comment by vrajat** [comment]
@yjagdale - Can you take a look? This must be solved as piicatcher now supports 3.9 and 3.10 as well.

@ian-lewis-d which type of machine did you try the command on?
